import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "contextBharat — AI Documentation for Indian APIs",
  description:
    "Razorpay, Zerodha Kite, ONDC, UPI, GST APIs instantly in Claude, Cursor, and VS Code. " +
    "Hindi documentation. Offline-first. Free to start.",
  keywords: "razorpay docs, zerodha kite api, ondc integration, upi api, indian api documentation, mcp server india",
  openGraph: {
    title: "contextBharat — AI Documentation for Indian APIs",
    description: "The documentation layer India's developers deserved. Razorpay, Zerodha, ONDC, UPI docs in your AI editor.",
    url: "https://contextbharat.com",
    siteName: "contextBharat",
    locale: "en_IN",
    type: "website",
    // OG image auto-generated by app/opengraph-image.tsx (Next.js file convention)
  },
  twitter: {
    card: "summary_large_image",
    title: "contextBharat — AI Documentation for Indian APIs",
    description: "Razorpay, ONDC, UPI, Zerodha docs in your AI editor. Free MCP server for Indian developers.",
    creator: "@contextbharat",
    // Twitter image auto-generated by app/opengraph-image.tsx (Next.js file convention)
  },
  metadataBase: new URL("https://contextbharat.com"),
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "contextBharat",
  description: "AI-native MCP documentation server for Indian APIs, government specs, and global frameworks.",
  url: "https://contextbharat.com",
  applicationCategory: "DeveloperApplication",
  operatingSystem: "macOS, Linux, Windows",
  inLanguage: ["en", "hi", "ta", "te", "kn", "bn"],
  offers: { "@type": "Offer", price: "0", priceCurrency: "INR" },
  author: {
    "@type": "Organization",
    name: "contextBharat",
    url: "https://contextbharat.com",
    sameAs: [
      "https://twitter.com/contextbharat",
      "https://github.com/contextbharat/context-bharat",
    ],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
